-- Run this SQL in Supabase SQL Editor.
create table if not exists profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text unique not null,
  display_name text,
  created_at timestamptz default now()
);
create table if not exists messages (
  id bigint generated by default as identity primary key,
  sender_id uuid references profiles(id) on delete cascade not null,
  receiver_id uuid references profiles(id) on delete cascade not null,
  content text not null,
  created_at timestamptz default now()
);
alter table profiles enable row level security;
alter table messages enable row level security;
create policy "profiles readable" on profiles for select to authenticated using (true);
create policy "own profile insert" on profiles for insert to authenticated with check (auth.uid()=id);
create policy "own profile update" on profiles for update to authenticated using (auth.uid()=id);
create policy "messages readable by participants" on messages for select to authenticated using (auth.uid()=sender_id or auth.uid()=receiver_id);
create policy "send own messages" on messages for insert to authenticated with check (auth.uid()=sender_id);
alter publication supabase_realtime add table messages;
